# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GPL-3.0-or-later"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader


[[mods]]
modId="bronzeage"
version="${file.jarVersion}"
displayName="The Bronze Age"
logoFile="bronzeagelogo.png"
credits="Special thanks to all contributors on GitHub"
authors="gApples13 (HB_Redstone in MC)"
description='''
The Bronze Age Mod for Minecraft Forge 1.18.2
Adds a useful metal to the game, making copper a little less useless.
Contribute On GitHub: https://github.com/gApples13/Bronze-Age-Mod

Warning! This is an open ALPHA TESTING VERSION. It's for TESTING ONLY, bugs and crashes are CERTAIN.
Only play on worlds you care about if you know what you're doing.
By playing this mod you agree that YOU ARE RESPONSIBLE for damage to your worlds.

The Bronze Age Copyright (C) 2022 Henry C
This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
This is free software, and you are welcome to redistribute it
under certain conditions; see COPYING for details.
'''

[[dependencies.bronzeage]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bronzeage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
